import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'

export function bundleGas() {
  const gas = readFileSync(new URL('../gas/Code.gs', import.meta.url), 'utf8')
  return '// Generated by npm run build:gas. Do not edit.\n' + gas
}

mkdirSync(new URL('../gas/dist/', import.meta.url), { recursive: true })
writeFileSync(new URL('../gas/dist/Code.gs', import.meta.url), bundleGas())
